apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    namespace: {{ .Values.namespace }}
    repo: {{ .Values.name }}
    ##----
    name: {{ .Values.metadata.name }}
    environment: {{ .Values.metadata.environment }}
    owner: {{ .Values.metadata.owner }}
    commit: {{ .Values.metadata.commit }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      imagePullSecrets:
          - name: ghcr-secret

      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.container.image }}
          ports:
            - containerPort: {{ .Values.container.port }}
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "250Mi"