apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ .Values.name }}-ingress" 
  namespace: {{ .Values.namespace }}
  labels:
    namespace: {{ .Values.namespace }}
    repo: {{ .Values.name }}
    ##----
    environment: {{ .Values.metadata.environment }}
    owner: {{ .Values.metadata.owner }}
    commit: {{ .Values.metadata.commit }}


  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: {{ .Values.ingress.entry }}

spec:
  entryPoints:
    - {{ .Values.ingress.entry }}
  routes:
    - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`{{ .Values.ingress.path }}`)
      kind: Rule
      services:
        - name: {{ .Values.name }}-svc
          port: {{ .Values.service.port }}