name: On-Premise deploy

on:
  push:
    branches: [ "main" ]

  #workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest #Runner cloud (default)
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Build in node
        uses: codeparce/ci-workflows/.github/actions/node/build@v1
        with:
          type: web-build
          target: dist

  docker-publish:
    needs: build
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest  #Runner cloud (default)
    steps:
      - uses: actions/checkout@v4
          
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: dist

      - name: Publish to Docker Hub
        uses: codeparce/ci-workflows/.github/actions/registry@v1
        with:
          container-access-token: ${{ secrets.CONTAINER_REGISTRY_PAT_GITHUB }}

  deploy:
    runs-on: kubernetes #Runner on-premise
    needs: docker-publish
    env:
      GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
      GITHUB_ORG: ${{ github.repository_owner }}
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Kubernetes
        run: | 
          cd helm 
          export IMAGE_TAG=${GITHUB_SHA::7}
          SVC_NAME=${GITHUB_REF_NAME}-svc
          NS=sis-${GITHUB_REF_NAME}-ms
            
          echo "Deploying ${GITHUB_REPOSITORY_NAME} to Kubernetes..."
          
          envsubst < values.template > values.yaml

          helm upgrade --install ${GITHUB_REPOSITORY_NAME} . --namespace $NS --create-namespace
          
          echo "Secret created."
          kubectl create secret docker-registry ghcr-secret \
            --docker-server=ghcr.io \
            --docker-username=${{ github.actor }} \
            --docker-password=${{ secrets.CONTAINER_REGISTRY_PAT_GITHUB }} \
            --namespace=$NS 

          echo "Deployment completed successfully."
          
          echo "DNS Externo: http://microservicio.${NS}.lab/users"

          echo "Domain interno: ${SVC_NAME}.${NS}.svc.cluster.local/users"